import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { Skill } from '../models/skill.model';
import { Certification } from '../models/certification.model';
import { ExperienceItem } from '../models/experience.model';
import { Project } from '../models/project.model';

@Injectable({
  providedIn: 'root',
})
export class Data {
  constructor() {}

  getSkills(): Observable<Skill[]> {
    const skills: Skill[] = [
      { id: 's1', name: 'Java', icon: 'logos:java' },
      { id: 's2', name: 'Spring Boot', icon: 'logos:spring' },
      { id: 's3', name: 'HTML', icon: 'logos:html-5' },
      { id: 's4', name: 'CSS', icon: 'logos:css-3' },
      { id: 's5', name: 'JavaScript', icon: 'logos:javascript' },
      { id: 's6', name: 'MySQL', icon: 'logos:mysql' },
      { id: 's7', name: 'Git', icon: 'logos:git' },
      { id: 's8', name: 'GitHub', icon: 'logos:github' },
      { id: 's9', name: 'Postman', icon: 'logos:postman' },
      { id: 's10', name: 'REST API', icon: 'mdi:api' },
      { id: 's11', name: 'Data Analytics', icon: 'logos:google-analytics' },
      { id: 's12', name: 'Angular', icon: 'logos:angular' },
      { id: 's13', name: 'Power BI', icon: 'assets/powerbi.svg' },
      { id: 's14', name: 'Excel', icon: 'assets/excel.svg' },
      { id: 's15', name: 'Looker Studio', icon: 'logos:google-analytics' },
      { id: 's16', name: 'FlutterFlow', icon: 'logos:flutter' },
      { id: 's17', name: 'Figma', icon: 'logos:figma' },
      { id: 's18', name: 'PHP', icon: 'logos:php' },
      { id: 's19', name: 'WordPress', icon: 'logos:wordpress' },
      { id: 's20', name: 'Tailwind', icon: 'logos:tailwindcss' },
    ];
    return of(skills);
  }

  getProjects(): Observable<Project[]> {
    const projects: Project[] = [
      {
        id: 'p1',
        title: 'Aplicación de Pokedex - Proyecto Personal',
        tags: ['App', 'Proyecto Personal'],
        description: 'Desarrollo de un dashboard en Power BI que visualiza la llegada de turistas internacionales al Perú, permitiendo a los usuarios analizar tendencias y patrones de turismo en el país.',
        tech: ['Flutter', 'Api', 'MySql'],
        demoUrl: '#',
        repoUrl: 'https://github.com/JSobero/app-pokedex.git',
        category: 'Mobile App',
      },
      {
        id: 'p2',
        title: 'Llegada de turistas internacionales al Perú - Proyecto Personal',
        tags: ['Data', 'Proyecto Personal'],
        description: 'Desarrollo de un dashboard en Power BI que visualiza la llegada de turistas internacionales al Perú, permitiendo a los usuarios analizar tendencias y patrones de turismo en el país.',
        tech: ['Power BI', 'Data Analytics'],
        demoUrl: 'https://app.powerbi.com/view?r=eyJrIjoiYzc3NzEyZDAtMWI5ZS00YjNkLTlhYmYtNWZmNThkZTg0ZWM4IiwidCI6ImM0YTY2YzM0LTJiYjctNDUxZi04YmUxLWIyYzI2YTQzMDE1OCIsImMiOjR9',
        repoUrl: '#',
        category: 'Data Science',
      },
      {
        id: 'p3',
        title: 'Dashboard de estaciones base en todo el Perú - Proyecto Personal',
        tags: ['Data', 'Proyecto Personal'],
        description: 'Desarrollo de un dashboard en Power BI que visualiza la ubicación y el estado de las estaciones base de telecomunicaciones en todo el Perú, permitiendo a los usuarios analizar la cobertura y el rendimiento de la red.',
        tech: ['Power BI', 'Data Analytics'],
        demoUrl: 'https://app.powerbi.com/view?r=eyJrIjoiZmFiYmQzMGMtNzJlNC00OGNmLTg3NjctZjY0ZjI1MWRjMWM5IiwidCI6ImM0YTY2YzM0LTJiYjctNDUxZi04YmUxLWIyYzI2YTQzMDE1OCIsImMiOjR9',
        repoUrl: '#',
        category: 'Data Science',
      },
      {
        id: 'p4',
        title: 'Dashboard de estaciones base en todo el Perú - Proyecto Personal',
        tags: ['Data', 'Proyecto Personal'],
        description: 'Desarrollo de un dashboard en Power BI que visualiza la ubicación y el estado de las estaciones base de telecomunicaciones en todo el Perú, permitiendo a los usuarios analizar la cobertura y el rendimiento de la red.',
        tech: ['Power BI', 'Data Analytics'],
        demoUrl: 'https://app.powerbi.com/view?r=eyJrIjoiZmFiYmQzMGMtNzJlNC00OGNmLTg3NjctZjY0ZjI1MWRjMWM5IiwidCI6ImM0YTY2YzM0LTJiYjctNDUxZi04YmUxLWIyYzI2YTQzMDE1OCIsImMiOjR9',
        repoUrl: '#',
        category: 'Data Science',
      },
      {
        id: 'p5',
        title: 'Dashboard de la visión y demanda global de un inventario - Proyecto Personal',
        tags: ['Data', 'Proyecto Personal'],
        description: 'Desarrollo de un dashboard en Power BI que proporciona una visión integral de la demanda global de un inventario, permitiendo a los usuarios analizar tendencias y patrones de consumo a nivel mundial.',
        tech: ['Power BI', 'Data Analytics'],
        demoUrl: 'https://app.powerbi.com/view?r=eyJrIjoiOTIyYTBhZDgtOWY5Ni00MjZhLWEzZWYtYzdkOGNhMGQ4YmVhIiwidCI6ImM0YTY2YzM0LTJiYjctNDUxZi04YmUxLWIyYzI2YTQzMDE1OCIsImMiOjR9',
        repoUrl: '#',
        category: 'Data Science',
      },
      {
        id: 'p6',
        title: 'Dashboard de la visión y demanda global de un inventario - Proyecto Personal" - Proyecto Personal',
        tags: ['Data', 'Proyecto Personal'],
        description: 'Desarrollo de un dashboard en Power BI que proporciona una visión integral de la demanda global de un inventario, permitiendo a los usuarios analizar tendencias y patrones de consumo a nivel mundial.',
        tech: ['Power BI', 'Data Analytics', 'Looker Studio'],
        demoUrl: '#',
        repoUrl: 'https://app.powerbi.com/view?r=eyJrIjoiOTIyYTBhZDgtOWY5Ni00MjZhLWEzZWYtYzdkOGNhMGQ4YmVhIiwidCI6ImM0YTY2YzM0LTJiYjctNDUxZi04YmUxLWIyYzI2YTQzMDE1OCIsImMiOjR9',
        category: 'Data Science',
      },
      {
        id: 'p7',
        title: 'Dashboard del balance financiero de la fundación "Potenciar Solidario" - Proyecto Personal',
        tags: ['Data', 'Proyecto Personal'],
        description: 'Desarrollo de un dashboard en Looker Studio para la fundación "Potenciar Solidario" que permite visualizar y analizar el balance financiero utilizando Excel y técnicas de análisis de datos.',
        tech: ['Excel', 'Data Analytics', 'Looker Studio'],
        demoUrl: '#',
        repoUrl: 'https://lookerstudio.google.com/s/iQcxLyqQaz4',
        category: 'Data Science',
      },
      {
        id: 'p8',
        title: 'Dashboard Proveedores y Donantes de la fundación "Potenciar Solidario" - Proyecto Personal',
        tags: ['Data', 'Proyecto Personal'],
        description: 'Desarrollo de un dashboard en Looker Studio para la fundación "Potenciar Solidario" que permite visualizar y analizar datos de proveedores y donantes utilizando Excel y técnicas de análisis de datos.',
        tech: ['Excel', 'Data Analytics', 'Looker Studio'],
        demoUrl: '#',
        repoUrl: 'https://lookerstudio.google.com/reporting/9aba2638-aab1-40e9-aeb0-0b2e1cc9e54d',
        category: 'Data Science',
      },
      {
        id: 'p9',
        title: 'Dashboard Proveedores y Donantes de la fundación "Potenciar Solidario" - Proyecto Personal',
        tags: ['Data', 'Proyecto Personal'],
        description: 'Desarrollo de un dashboard para la fundación "Potenciar Solidario" que permite visualizar y analizar datos de proveedores y donantes utilizando Excel y técnicas de análisis de datos.',
        tech: ['Excel', 'Data Analytics'],
        demoUrl: '#',
        repoUrl: 'https://docs.google.com/spreadsheets/d/1OqT2TQdxvibxpmMkCICtGSEfBPiThJYUpyQpOBIz3tU/edit?usp=sharing',
        category: 'Data Science',
      },
      {
        id: 'p10',
        title: 'Landing Page de Juegos (Colaborador) - Proyecto Personal',
        tags: ['Desarrollo Web', 'Proyecto Personal', 'Colaborador'],
        description: 'Desarrollo de una landing page para un sitio web de juegos utilizando Astro y Tailwind CSS, que presenta una colección de juegos interactivos y atractivos para los usuarios.',
        tech: ['Astro', 'Tailwind'],
        demoUrl: '#',
        repoUrl: 'https://github.com/ieeecsutpdev/Egames.git',
        category: 'Web Dev',
      },
      {
        id: 'p11',
        title: 'Almacen de Hardware (Colaborador) - Proyecto Académico',
        tags: ['Desarrollo Web', 'Proyecto Académico', 'Colaborador'],
        description: 'Desarrollo de una aplicación web para la gestión de un almacén de hardware utilizando Spring Boot y Angular, que permite a los usuarios administrar inventarios, realizar pedidos y gestionar proveedores.',
        tech: ['Spring Boot', 'Angular', 'API REST', 'IA', 'TypeScript', 'HTML', 'Tailwind'],
        demoUrl: '#',
        repoUrl: 'https://github.com/Mauricio-Millan/PRJ-Almacen-de-Hardware.git',
        category: 'Web Dev',
      },
      {
        id: 'p12',
        title: 'Dashboard Planificador de Viaje - Proyecto Académico',
        tags: ['Desarrollo Web', 'Proyecto Académico'],
        description: 'Desarrollo de una aplicación web para planificar viajes utilizando Python y Flask, que permite a los usuarios buscar destinos y analizar toda información de ella para sus viajes.',
        tech: ['Python', 'Flask', 'API REST', 'IA', 'JavaScript', 'HTML', 'CSS'],
        demoUrl: '#',
        repoUrl: 'https://github.com/JSobero/planificador_de_viaje.git',
        category: 'Web Dev',
      },
      {
        id: 'p13',
        title: 'Sistema de eventos de voluntariado - Proyecto Académico',
        tags: ['Desarrollo Web', 'Proyecto Académico'],
        description: 'Desarrollo de una aplicación web para la gestión de eventos de voluntariado utilizando Spring Boot y Angular, que permite a los usuarios registrarse, crear y administrar eventos, así como gestionar la participación de voluntarios.',
        tech: ['Spring Boot', 'Angular', 'API REST', 'IA', 'TypeScript', 'Docker', 'HTML', 'Tailwind'],
        demoUrl: '#',
        repoUrl: 'https://github.com/JSobero/voluntariado.git',
        category: 'Web Dev',
      },
      {
        id: 'p14',
        title: 'Delicius Catering - Proyecto Académico',
        tags: ['Desarrollo Web', 'Proyecto Académico'],
        description: 'Desarrollo de una aplicación web para la gestión de pedidos y administración de un servicio de catering, utilizando Python y Flask, que permite a los usuarios realizar pedidos en línea, gestionar menús y administrar eventos.',
        tech: ['Python', 'MySQL', 'Flask', 'IA'],
        demoUrl: '#',
        repoUrl: 'https://github.com/JSobero/delicius-catering-sistemas-curso-dise-o.git',
        category: 'Web Dev',
      },
      {
        id: 'p15',
        title: 'Consulta de Datos Personales - Proyecto Académico',
        tags: ['Desarrollo Web', 'Proyecto Académico'],
        description: 'Desarrollo de una aplicación web para la consulta de datos personales utilizando PHP y MySQL, que permite a los usuarios ingresar su número de documento y obtener información relevante almacenada en la base de datos.',
        tech: ['PHP', 'MySQL', 'Bootstrap', 'html5-qrcode', 'SweetAlert', 'IA'],
        demoUrl: '#',
        repoUrl: 'https://github.com/JSobero/integrador-web.git',
        category: 'Web Dev',
      },
      {
        id: 'p16',
        title: 'Hotel Serenia Oasis - Proyecto Personal',
        tags: ['Desarrollo Web', 'Proyecto Personal'],
        description: 'Desarrollo de una aplicación web para la gestión de reservas y administración de un hotel, utilizando PHP y MySQL, que permite a los usuarios realizar reservas en línea, gestionar habitaciones y servicios, y generar reportes de ocupación y facturación.',
        tech: ['PHP', 'MySQL', 'Bootstrap', 'FPDF', 'SweetAlert'],
        demoUrl: '#',
        repoUrl: 'https://github.com/JSobero/Hotel-Tesina.git',
        category: 'Web Dev',
      },
      {
        id: 'p17',
        title: 'LiterAlura - Alura Latam',
        tags: ['API RESTful', 'Proyecto', 'Reto'],
        description: 'Desarrollo de una API RESTful para la gestión de una biblioteca digital utilizando Java y Spring Boot, que permite a los usuarios buscar, agregar, actualizar y eliminar libros de la colección.',
        tech: ['Java SpringBoot', 'API RESTful', 'CRUD', 'Postman', 'PostgreSQL'],
        demoUrl: '#',
        repoUrl: 'https://github.com/JSobero/LiterAlura-Challengue.git',
        category: 'API REST',
      },
      {
        id: 'p18',
        title: 'ForoHub - Alura Latam',
        tags: ['API RESTful', 'Proyecto', 'Reto'],
        description: 'Desarrollo de una API RESTful para un foro de discusión utilizando Java y Spring Boot, que permite a los usuarios crear, leer, actualizar y eliminar temas y respuestas en el foro.',
        tech: ['Java SpringBoot', 'API RESTful', 'CRUD', 'Postman'],
        demoUrl: '#',
        repoUrl: 'https://github.com/JSobero/Challengue-ForoHub.git',
        category: 'API REST',
      },
      {
        id: 'p19',
        title: 'Conversor de Moneda - Alura Latam',
        tags: ['Aplicación de Consola', 'Proyecto', 'Reto'],
        description: '',
        tech: ['Java'],
        demoUrl: '#',
        repoUrl: 'https://github.com/JSobero/Conversor.git',
        category: 'Desktop App',
      },
      {
        id: 'p20',
        title: 'Generador de QR - Proyecto Personal',
        tags: ['Aplicación de Escritorio', 'Proyecto Personal'],
        description: 'Desarrollo de una aplicación de escritorio para generar códigos QR personalizados utilizando Python y la biblioteca Tkinter, que permite a los usuarios crear códigos QR para URLs, texto y otros datos de manera sencilla y rápida.',
        tech: ['Python', 'Tkinter'],
        demoUrl: '#',
        repoUrl: 'https://github.com/JSobero/calculadora-moderna.git',
        category: 'Desktop App',
      },
      {
        id: 'p21',
        title: 'Portafolio Web usando Bootstrap - Proyecto Académico',
        tags: ['Desarrollo Web', 'Proyecto Académico', 'Plantilla Bootstrap'],
        description: 'Desarrollo de un portafolio web utilizando una plantilla Bootstrap para mostrar mis proyectos y habilidades en desarrollo web, con un diseño responsivo y moderno.',
        tech: ['CSS', 'HTML', 'Bootstrap', 'JavaScript'],
        demoUrl: 'https://jsobero.github.io/portafolio-bootstrap/',
        repoUrl: 'https://github.com/JSobero/portafolio-bootstrap.git',
        category: 'Desktop App',
      },
      {
        id: 'p22',
        title: 'Aplicación de Gestión de Ventas - Proyecto Personal',
        tags: ['Aplicación de Escritorio', 'Proyecto Personal'],
        description: 'Desarrollo de una aplicación de escritorio para la gestión de ventas utilizando C# y Windows Forms, que permite registrar productos, clientes y ventas, generando reportes de ventas diarias.',
        tech: ['C#', 'Microsoft SQL Server'],
        demoUrl: '#',
        repoUrl: 'https://github.com/JSobero/sistema-de-ventas.git',
        category: 'Desktop App',
      },
      {
        id: 'p23',
        title: 'Página Web sobre mis Actividades Realizadas en clase - Proyecto Académico',
        tags: ['Desarrollo Web', 'Proyecto Académico', 'Bootstrap'],
        description: 'Desarrollo de una página web utilizando una plantilla Bootstrap para presentar las actividades realizadas durante el curso de Desarrollo Web, incluyendo proyectos, ejercicios y recursos educativos.',
        tech: ['JavaScript', 'CSS', 'HTML', 'Bootstrap'],
        demoUrl: 'https://jsobero.github.io/cuaderno-de-trabajo/',
        repoUrl: 'https://github.com/JSobero/cuaderno-de-trabajo.git',
        category: 'Web Dev',
      },
      {
        id: 'p24',
        title: 'Gestión de ventas de tienda técnologica usando CRUD- Proyecto Académico',
        tags: ['Desarrollo Web', 'Proyecto Académico', 'CRUD'],
        description: 'Desarrollo de una aplicación web para la gestión de ventas en una tienda tecnológica, implementando funcionalidades CRUD (Crear, Leer, Actualizar, Eliminar) para administrar productos, clientes y ventas.',
        tech: ['JavaScrip', 'CSS', 'HTML', 'C#', 'Bootstrap', 'ASP'],
        demoUrl: '#',
        repoUrl: 'https://github.com/JSobero/CRUD-gestion-ventas-tienda.git',
        category: 'Web Dev',
      },
      {
        id: 'p25',
        title: 'Sistema de Almacén para Tienda de Utensilios de Limpieza - Proyecto Académico',
        tags: ['Aplicación de Escritorio', 'Proyecto Académico'],
        description: 'Desarrollo de un sistema de almacén para una tienda de utensilios de limpieza utilizando .NET y MySql, permitiendo gestionar inventarios, ventas y proveedores de manera eficiente.',
        tech: ['.NET', 'MySql'],
        demoUrl: '#',
        repoUrl: 'https://github.com/JSobero/sistema-almacen-tienda-de-utensilios-de-limpieza.git',
        category: 'Desktop App',
      },
      {
        id: 'p26',
        title: 'Juego De La Serpiente - Proyecto Personal',
        tags: ['Desarrollo Web', 'Proyecto', 'Reto'],
        description: 'Juego clásico de la serpiente desarrollado como proyecto personal para practicar habilidades de programación web, me apoye de un video de youtube.',
        tech: ['JavaScrip', 'CSS', 'HTML'],
        demoUrl: 'https://jsobero.github.io/Juego-snake/',
        repoUrl: 'https://github.com/JSobero/Juego-snake.git',
        category: 'Web Dev',
      },
      {
        id: 'p27',
        title: 'Lista de Tareas - Alura Latam',
        tags: ['Desarrollo Web', 'Proyecto', 'Reto'],
        description: 'Aplicación web para gestionar una lista de tareas, desarrollada como parte del curso de Alura Latam.',
        tech: ['JavaScrip', 'CSS', 'HTML'],
        demoUrl: 'https://jsobero.github.io/Almacenado-de-datos-en-una-lista/',
        repoUrl: 'https://github.com/JSobero/Almacenado-de-datos-en-una-lista.git',
        category: 'Web Dev',
      },
      {
        id: 'p28',
        title: 'Ahorcado (Juego) - Alura Latam',
        tags: ['Desarrollo Web', 'Proyecto', 'Reto'],
        description: 'Juego clásico del ahorcado desarrollado como parte del curso de Alura Latam.',
        tech: ['JavaScrip', 'CSS', 'HTML'],
        demoUrl: 'https://jsobero.github.io/Juego-Ahorcado/',
        repoUrl: 'https://github.com/JSobero/Juego-Ahorcado.git',
        category: 'Web Dev',
      },
      {
        id: 'p29',
        title: 'Dashboard de la base de datos Tienda Aurelion - Proyecto Guayerd',
        tags: ['Data', 'Proyecto Personal'],
        description: 'Desarrollo de un dashboard en Power BI que proporciona una visión integral de las ventas, productos y clientes, permitiendo al cliente analizar tendencias y patrones de consumo para la toma de decisiones informadas.',
        tech: ['Power BI', 'Data Analytics', 'Python'],
        demoUrl: 'https://app.powerbi.com/view?r=eyJrIjoiODhlYzA3YjctM2ZjNi00MjFmLWEyOTktMmI3NDE3ZmYxOWRhIiwidCI6ImM0YTY2YzM0LTJiYjctNDUxZi04YmUxLWIyYzI2YTQzMDE1OCIsImMiOjR9',
        repoUrl: '#',
        category: 'Data Science',
      },
    ];
    return of(projects);
  }

  getExperience(): Observable<ExperienceItem[]> {
    const exp: ExperienceItem[] = [
      {
        id: 'e4',
        period: 'Mayo 2025 - Setiembre 2025',
        title: 'Operador de Cámaras y GPS',
        company: 'MUNICIPALIDAD DE CHORRILLOS',
        bullets: [
          'Supervisé sistemas de videovigilancia y rastreo GPS, asegurando el funcionamiento de cámaras y software especializado.',
          'Brindé soporte técnico al personal operativo.',
        ],
      },
      {
        id: 'e3',
        period: 'Setiembre 2024 - Diciembre 2024',
        title: 'Coordinador de Innovación y Soporte Tecnológico',
        company: 'UGEL 02',
        bullets: [
          'Coordiné el mantenimiento e instalación de equipos tecnológicos, brindé soporte al personal docente y promoví el uso de herramientas digitales y TIC en la institución.',
        ],
      },
      {
        id: 'e2',
        period: 'Diciembre 2022 - Mayo 2023',
        title: 'Técnico en Computación e Informática',
        company: 'KM INGENIEROS Y CONSTRUCTORES',
        bullets: [
          'Ejecuté tareas de soporte técnico, mantenimiento de hardware y software, y administración de redes.',
          'Implementé soluciones básicas de programación y optimización de procesos informáticos.',
        ],
      },
      {
        id: 'e1',
        period: 'Enero 2022 - Enero 2023',
        title: 'Asistente Administrativo',
        company: 'SERVICIOS DE PREPARACIÓN ACADÉMICA',
        bullets: [
          'Brindé soporte técnico y administrativo, realizando mantenimiento de equipos, instalación de redes y gestión de bases de datos.',
          'Contribuí a la digitalización de documentos y mejora de procesos internos.',
        ],
      },
    ];
    return of(exp);
  }

  getCertifications(): Observable<Certification[]> {
    return of([
      {
        id: 'c1',
        name: 'Curso: Excel básico, Intermedio y Avanzado (octubre 2021 – diciembre 2021)',
        org: 'IESTP ANTENOR ORREGO ESPINOZA - CHORRILLOS',
      },
      {
        id: 'c2',
        name: 'Especialización: Tecnología De La Información Y Comunicación (diciembre 2023 - diciembre 2024)',
        org: 'UNIVERSIDAD NACIONAL DE EDUCACIÓN ENRIQUE GUZMÁN Y VALLE',
      },
      {
        id: 'c3',
        name: "Capacitación: Aula De Innovación Pedagógica Para El Fortalecimiento De Las TIC'S (enero 2024 - febrero 2024)",
        org: 'UNIVERSIDAD NACIONAL DE EDUCACIÓN ENRIQUE GUZMÁN Y VALLE',
      },
      {
        id: 'c4',
        name: 'Curso: Soporte Técnico Remoto de Computadoras (marzo 2024 - abril 2024)',
        org: 'LIMA EDUCA',
      },
      {
        id: 'c5',
        name: 'Curso: Administración y atención al cliente (abril 2024)',
        org: 'CONECTA EMPLEO',
      },
      {
        id: 'c6',
        name: 'Curso: Gestión de Proyectos con Metodologías Ágiles y Enfoques Lean (mayo 2024)',
        org: 'CONECTA EMPLEO',
      },
      { id: 'c7', name: 'Curso: Office Básico (junio 2021)', org: 'CONECTA EMPLEO' },
      {
        id: 'c8',
        name: 'Curso: Backend (enero 2024 - julio 2024)',
        org: 'Oracle Next Education - Alura',
      },
      {
        id: 'c9',
        name: 'Curso: Reparación de Computadoras Desde Cero (agosto 2024)',
        org: 'UDEMY',
      },
      {
        id: 'c10',
        name: 'Curso: ASISTENTE DE DOCENCIA EN ALGORÍTMICA (agosto 2024)',
        org: 'UNIVERSIDAD TECNOLOGICA DEL PERU',
      },
      {
        id: 'c11',
        name: 'Diplomado: Fundamentos de Data Analytics (junio 2024 - noviembre 2024)',
        org: 'Guayerd y IBM SkillsBuild',
      },
      {
        id: 'c12',
        name: 'Curso: Generación IA: el ABC de la Inteligencia Artificial Generativa (Julio 2025)',
        org: 'Eidos Global y Microsoft',
      },
      {
        id: 'c13',
        name: 'Curso: Introducción al Internet de las Cosas y Transformación Digital (Mayo 2025)',
        org: 'Cisco',
      },
      {
        id: 'c14',
        name: 'Curso: Desarrollo de Juegos Core: Threadbare (Julio 2025)',
        org: 'Endless Foundation',
      },
      { id: 'c15', name: 'Curso: Marketing Digital (Junio 2025)', org: 'Minedu' },
    ]);
  }
}
